### ISSUE TITLE
No IMU messages to process

### ISSUE THREAD

**Issue by mjunsen123** [Autoliv-Research/allan_variance_ros2#3]
Hi, can you please help me with this issue

[INFO] [1714640070.508600182] [rclcpp]: Bag Path = ros2_output/ros2_output_0.mcap
[INFO] [1714640070.508651066] [rclcpp]: Config File = /home/jyee/ros2_ws/src/allan_variance_ros2/config/customConfig.yaml
[INFO] [1714640070.521048855] [rclcpp]: imu_topic: /imu
[INFO] [1714640070.521114222] [rclcpp]: imu_rate: 285
[INFO] [1714640070.521135828] [rclcpp]: measure_rate: 200
[INFO] [1714640070.521153451] [rclcpp]: sequence_duration: 0
[INFO] [1714640070.521168783] [rclcpp]: sequence_offset: 0
[INFO] [1714640070.521198806] [rclcpp]: Computor constructed
[INFO] [1714640070.521212476] [rclcpp]: Processing rosbag ros2_output/ros2_output_0.mcap
[INFO] [1714640070.521226359] [rclcpp]: Processing ros2_output/ros2_output_0.mcap ...
[INFO] [1714640070.525722572] [rclcpp]: Topic /imu found in the bag!
[INFO] [1714640070.527614583] [rclcpp]: Finished buffering data. 0 measurements
**[ERROR] [1714640070.527660973] [rclcpp]: No IMU messages to process, is your topic right?**
[INFO] [1714640070.527678761] [rclcpp]: Total computation time: 0.005454 s
[INFO] [1714640070.527696279] [rclcpp]: Data written to allan_variance.csv

**my config:**
imu_topic: "/imu"
imu_rate: 285
measure_rate: 200 # Rate to which imu data is subsampled
sequence_time: 9839 # 3 hours in seconds

**my bag info**
Files:             ros2_output_0.mcap
Bag size:          1017.5 MiB
Storage id:        mcap
Duration:          9839.580s
Start:             May  1 2024 13:10:30.609 (1714565430.609)
End:               May  1 2024 15:54:30.190 (1714575270.190)
Messages:          2814490
Topic information: Topic: /imu | Type: sensor_msgs/msg/Imu | Count: 2814490 | Serialization Format: cdr

**Comment by christian-nils** [comment]
Hi @mjunsen123,

Sorry I missed your message. I believe the issue may be that only allan_variance_msgs/msg/Imu9DoF are today accounted for. I am planning to reintroduce the standard IMU message in the future. But I cannot tell when.
